### ISSUE TITLE
Create app starter kit or development environment

### ISSUE THREAD

**Issue by joshmorel** [chingu-coders/voyage1-turtles-team-38#1]
Consider either: 

* create-react-app
* https://www.npmjs.com/package/react-chrome-extension-boilerplate
* custom

**Comment by joshmorel** [comment]
@wjhurley 

I forgot to create a feature-branch (aka topic/issue branch) and ended up pushing to master. At this point no biggie but I made it a protected branch now so we'll need to merge from a feature branch here on out and perform a merge request.

Anyways, take a look and see if it works locally. [create-react-app](https://github.com/facebookincubator/create-react-app) is a pretty awesome choice for making the tooling set-up easy!

**Comment by wjhurley** [comment]
@joshmorel 
The setup looks good and both `npm install` to install dependencies and `npm start` to start the dev server worked fine for me. I like how the App.js file is commented so we have an idea of how the app will be structured.
